/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LaterRouteImport } from './routes/later'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as PairRouteImport } from './routes/pair'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFacebookCallbackRouteImport } from './routes/api/facebook/callback'
import { Route as ApiFacebookStartRouteImport } from './routes/api/facebook/start'
import { Route as ApiSyncPairRouteImport } from './routes/api/sync/pair'
import { Route as ApiSyncSnapshotRouteImport } from './routes/api/sync/snapshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LaterRoute = LaterRouteImport.update({
  id: '/later',
  path: '/later',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookCallbackRoute = ApiFacebookCallbackRouteImport.update({
  id: '/api/facebook/callback',
  path: '/api/facebook/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookStartRoute = ApiFacebookStartRouteImport.update({
  id: '/api/facebook/start',
  path: '/api/facebook/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncPairRoute = ApiSyncPairRouteImport.update({
  id: '/api/sync/pair',
  path: '/api/sync/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncSnapshotRoute = ApiSyncSnapshotRouteImport.update({
  id: '/api/sync/snapshot',
  path: '/api/sync/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/composer': typeof ComposerRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/merchandise': typeof MerchandiseRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/vault': typeof VaultRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/facebook/start': typeof ApiFacebookStartRoute
  '/api/sync/pair': typeof ApiSyncPairRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/composer': typeof ComposerRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/merchandise': typeof MerchandiseRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/vault': typeof VaultRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/facebook/start': typeof ApiFacebookStartRoute
  '/api/sync/pair': typeof ApiSyncPairRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/composer': typeof ComposerRoute
  '/drafts': typeof DraftsRoute
  '/inbox': typeof InboxRoute
  '/later': typeof LaterRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/merchandise': typeof MerchandiseRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/vault': typeof VaultRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/facebook/callback': typeof ApiFacebookCallbackRoute
  '/api/facebook/start': typeof ApiFacebookStartRoute
  '/api/sync/pair': typeof ApiSyncPairRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/calendar'
    | '/composer'
    | '/drafts'
    | '/inbox'
    | '/later'
    | '/login'
    | '/media'
    | '/merchandise'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/vault'
    | '/api/auth/$'
    | '/api/facebook/callback'
    | '/api/facebook/start'
    | '/api/sync/pair'
    | '/api/sync/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/analytics'
    | '/calendar'
    | '/composer'
    | '/drafts'
    | '/inbox'
    | '/later'
    | '/login'
    | '/media'
    | '/merchandise'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/vault'
    | '/api/auth/$'
    | '/api/facebook/callback'
    | '/api/facebook/start'
    | '/api/sync/pair'
    | '/api/sync/snapshot'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/calendar'
    | '/composer'
    | '/drafts'
    | '/inbox'
    | '/later'
    | '/login'
    | '/media'
    | '/merchandise'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/vault'
    | '/api/auth/$'
    | '/api/facebook/callback'
    | '/api/facebook/start'
    | '/api/sync/pair'
    | '/api/sync/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ComposerRoute: typeof ComposerRoute
  DraftsRoute: typeof DraftsRoute
  InboxRoute: typeof InboxRoute
  LaterRoute: typeof LaterRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  MerchandiseRoute: typeof MerchandiseRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  VaultRoute: typeof VaultRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFacebookCallbackRoute: typeof ApiFacebookCallbackRoute
  ApiFacebookStartRoute: typeof ApiFacebookStartRoute
  ApiSyncPairRoute: typeof ApiSyncPairRoute
  ApiSyncSnapshotRoute: typeof ApiSyncSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/later': {
      id: '/later'
      path: '/later'
      fullPath: '/later'
      preLoaderRoute: typeof LaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/callback': {
      id: '/api/facebook/callback'
      path: '/api/facebook/callback'
      fullPath: '/api/facebook/callback'
      preLoaderRoute: typeof ApiFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/start': {
      id: '/api/facebook/start'
      path: '/api/facebook/start'
      fullPath: '/api/facebook/start'
      preLoaderRoute: typeof ApiFacebookStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/pair': {
      id: '/api/sync/pair'
      path: '/api/sync/pair'
      fullPath: '/api/sync/pair'
      preLoaderRoute: typeof ApiSyncPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/snapshot': {
      id: '/api/sync/snapshot'
      path: '/api/sync/snapshot'
      fullPath: '/api/sync/snapshot'
      preLoaderRoute: typeof ApiSyncSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ComposerRoute: ComposerRoute,
  DraftsRoute: DraftsRoute,
  InboxRoute: InboxRoute,
  LaterRoute: LaterRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  MerchandiseRoute: MerchandiseRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  VaultRoute: VaultRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFacebookCallbackRoute: ApiFacebookCallbackRoute,
  ApiFacebookStartRoute: ApiFacebookStartRoute,
  ApiSyncPairRoute: ApiSyncPairRoute,
  ApiSyncSnapshotRoute: ApiSyncSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
